# Generated by Django 3.2.14 on 2022-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf82', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf82',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
