# Generated by Django 3.2.14 on 2022-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hd_code', models.CharField(max_length=6)),
                ('watercycle_spring', models.CharField(max_length=6)),
                ('watercycle_summer', models.CharField(max_length=6)),
                ('watercycle_autumn', models.CharField(max_length=6)),
                ('watercycle_winter', models.CharField(max_length=6)),
                ('specl_manage_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
