# Generated by Django 3.2.14 on 2022-07-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planted_date', models.DateTimeField()),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.plants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_water', models.BooleanField(default=False)),
                ('state_led', models.BooleanField(default=False)),
                ('moisture_level', models.IntegerField()),
                ('last_watering', models.DateTimeField(auto_now=True)),
                ('my_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.myplant')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('photo', models.TextField()),
                ('diary_created_at', models.DateTimeField(auto_now_add=True)),
                ('diary_updated_at', models.DateTimeField(auto_now=True)),
                ('public_private', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.myplant')),
            ],
        ),
    ]
