# Generated by Django 3.2.14 on 2022-07-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20220725_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensing',
            name='my_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.myplant', unique=True),
        ),
    ]
