# Generated by Django 3.2.14 on 2022-07-18 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_diary_myplant_sensing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplant',
            name='planted_date',
        ),
        migrations.AddField(
            model_name='myplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myplant',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plants.plants'),
        ),
    ]
