# Generated by Django 3.2.14 on 2022-07-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_sensing_my_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensing',
            name='my_plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.myplant'),
        ),
    ]
