# Generated by Django 3.2.14 on 2022-07-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20220718_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_updated_at',
        ),
    ]
