# Generated by Django 3.2.14 on 2022-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_diary_diary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
