# Generated by Django 3.2.14 on 2022-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_myplant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
