# Generated by Django 3.2.14 on 2022-07-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='myplant',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
